version: '3'
services:
  app:
    image: public.ecr.aws/m5f1e7g7/ci-project-templates-full:version1.0
    volumes:
      - "/tmp/postgres/socket:/var/run/postgresql"
 
  psql:
    image: postgres:11.9
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=cistudent
      - POSTGRES_PASSWORD=pass1234
    network_mode: service:app
    volumes:
      - "/workspace/db-data:/var/lib/postgresql/data"
      - "/tmp/postgres/socket:/var/run/postgresql"
